name = "rag-api-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"

[env.production]
routes = [
  { pattern = "api.rag-cloudflare.pages.dev", zone_name = "rag-cloudflare.pages.dev" }
]

[[kv_namespaces]]
binding = "RAG_DATA"
id = "your_kv_namespace_id_here"  # Will be created
preview_id = "your_kv_namespace_id_here"

[vars]
ENVIRONMENT = "production"
AUTORAG_API_KEY = "your_autorag_api_key_here"
GOVINFO_API_KEY = "your_govinfo_api_key_here"
