name: Deploy RAG Services to Cloudflare

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install wrangler
        run: npm install -g wrangler
      - name: Publish Worker
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          cd scripts/cloudflare
          wrangler publish --env production
          wrangler secret:put RAG_SERVICE_URL --env production
          wrangler secret:put INGESTOR_SERVICE_URL --env production
