name: Build and push Docker images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      matrix:
        include:
          - name: frontend
            context: frontend
            dockerfile: frontend/Dockerfile
            image: ghcr.io/${{ github.repository_owner }}/rag-frontend:${{ github.sha }}
          - name: rag-server
            context: src/nvidia_rag/rag_server
            dockerfile: src/nvidia_rag/rag_server/Dockerfile
            image: ghcr.io/${{ github.repository_owner }}/rag-server:${{ github.sha }}
          - name: ingestor-server
            context: src/nvidia_rag/ingestor_server
            dockerfile: src/nvidia_rag/ingestor_server/Dockerfile
            image: ghcr.io/${{ github.repository_owner }}/ingestor-server:${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ matrix.image }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
