name: Run ingest

on:
  workflow_dispatch:
    inputs:
      source:
        required: true
        default: govinfo
        description: source to ingest (govinfo|congress|worker)
      path:
        required: false
        default: /collections/BILLS

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install requirements
        run: python -m pip install requests
      - name: Run ingest
        env:
          GOVINFO_API_KEY: ${{ secrets.GOVINFO_API_KEY }}
        run: |
          python3 scripts/ingest/gov_ingest.py --source ${{ github.event.inputs.source }} --path "${{ github.event.inputs.path }}" --api-key "$GOVINFO_API_KEY" --out out.ndjson
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ingest-out
          path: out.ndjson
